name: PMD Code Analysis

on:
  push:
    branches:
      - '**'  # Triggers on every branch

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0/pmd-bin-7.0.0.zip
          unzip pmd-bin-7.0.0.zip
          echo "$(pwd)/pmd-bin-7.0.0/bin" >> $GITHUB_PATH


      - name: Run PMD Analysis
        run: |
          pmd-bin-7.0.0-rc4/bin/run.sh pmd -d ./src -R rulesets/java/quickstart.xml -f text
